resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git
    branch: master
- name: pipeline
  type: git
  source:
    uri: https://github.com/dlapiduz/cf-continuous-test.git
    branch: master
- name: every-10-minutes
  type: time
  source:
    interval: 10m
- name: slack-alert
  type: slack-notification
  source:
    url: {{slack_hook_url}}
- name: stats-bucket
  type: s3
  source:
    bucket: {{stats_bucket_name}}
    regexp: build-time-(.*).txt
    access_key_id: {{stats_access_key_id}}
    secret_access_key: {{stats_secret_access_key}}
    private: true
jobs:
- name: run-smoke-tests
  build_logs_to_retain: 250
  plan:
  - get: cf-smoke-tests
  - get: pipeline
    trigger: true
  - get: every-10-minutes
    trigger: true
  - task: run-smoke-tests
    file: pipeline/tasks/run-smoke-tests.yml
    params:
      API_URI: {{api_uri}}
      APPS_DOMAIN: {{apps_domain}}
      CF_USER: {{cf_user}}
      CF_PASSOWRD: {{cf_password}}
      CF_ORG: {{cf_org}}
      CF_SPACE: {{cf_space}}
  - put: stats-bucket
    params:
      file: run-stats/build-time-*.txt
  on_success:
    put: slack-alert
    params:
      text_file: run-stats/build-time-*.txt
      icon_emoji: ":hospital:"
      username: Health Bot
      text: |
        :+1: Smoke tests passed succesfully ($TEXT_FILE_CONTENT): <$ATC_EXTERNAL_URL/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View Build>
  on_failure:
    put: slack-alert
    params:
      text_file: run-stats/build-time-*.txt
      icon_emoji: ":hospital:"
      username: Health Bot
      text: |
        :red_circle: Smoke tests failed ($TEXT_FILE_CONTENT): <$ATC_EXTERNAL_URL/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View Build>
